In [5]:
from ultralytics import YOLO


# Load the exported ONNX model
onnx_model = YOLO(r"ultralytics\best.onnx",task="detect")

# Run inference
results = onnx_model(r"ultralytics\dataset\images\val\pitted_surface_77.jpg")

Loading ultralytics\best.onnx for ONNX Runtime inference...
Using ONNX Runtime 1.23.2 with CUDAExecutionProvider

image 1/1 d:\A-project\YOLO-for-NEU-DET-dataset\ultralytics\dataset\images\val\pitted_surface_77.jpg: 224x224 2 pitted_surfaces, 57.5ms
Speed: 1.2ms preprocess, 57.5ms inference, 1.2ms postprocess per image at shape (1, 3, 224, 224)


In [10]:
results

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'crazing', 1: 'inclusion', 2: 'patches', 3: 'pitted_surface', 4: 'rolled-in_scale', 5: 'scratches'}
 obb: None
 orig_img: array([[[242, 242, 242],
         [241, 241, 241],
         [231, 231, 231],
         ...,
         [197, 197, 197],
         [202, 202, 202],
         [207, 207, 207]],
 
        [[244, 244, 244],
         [239, 239, 239],
         [233, 233, 233],
         ...,
         [205, 205, 205],
         [209, 209, 209],
         [205, 205, 205]],
 
        [[240, 240, 240],
         [235, 235, 235],
         [235, 235, 235],
         ...,
         [199, 199, 199],
         [203, 203, 203],
         [198, 198, 198]],
 
        ...,
 
        [[231, 231, 231],
         [240, 240, 240],
         [228, 228, 228],
         ...,
         [189, 189, 189],
         [190, 190, 190],
         [189, 189, 189]],
 
        [[230, 230, 

In [ ]:
import onnxruntime as ort
import numpy as np
from PIL import Image

# 加载 ONNX 模型
session = ort.InferenceSession(r"ultralytics\best.onnx", providers=['CPUExecutionProvider'])

# 预处理图片 
img = Image.open(r"ultralytics\dataset\images\val\pitted_surface_77.jpg").resize((224, 224))
img_array = np.array(img).transpose(2, 0, 1)[np.newaxis, ...].astype(np.float32) / 255.0

# 推理
outputs = session.run(None, {"images": img_array})

d:\anaconda3\envs\s\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(


In [ ]:
predictions = outputs[0][0]  # 输出形状: (300, 6)
confidence_threshold = 0.5
# [x, y, w, h, conf, class]
valid_predictions = predictions[predictions[:, 4] > confidence_threshold]

print(valid_predictions)

[[   -0.82776    0.005127      132.65      223.95     0.88733           3]
 [     137.83      1.4649      224.85       142.3     0.67083           3]]


In [74]:
results=predictions[predictions[:, 4] > confidence_threshold]

In [77]:
results

array([[   -0.82776,    0.005127,      132.65,      223.95,     0.88733,           3],
       [     137.83,      1.4649,      224.85,       142.3,     0.67083,           3]], dtype=float32)

In [83]:
results[0][0:3]

array([   -0.82776,    0.005127,      132.65], dtype=float32)

In [88]:
len(results)

2

In [ ]:
# boxxyxy=[]
# boxconf=[]
# boxcls=[]


In [117]:
boxb=[]
for r in results:
    boxarray=[]
    boxxyxy=r[0:3].tolist()
    boxconf=r[4].tolist()
    boxcls=r[5].tolist()
    boxarray.append(boxxyxy)
    boxarray.append(boxconf)
    boxarray.append(boxcls)
    boxb.append(boxarray)


In [126]:
boxb[0]

[[-0.8277587890625, 0.005126953125, 132.6519012451172],
 0.8873264789581299,
 3.0]

In [121]:
array[0]

[[0.0, 0.0, 119.03095245361328, 200.0], 0.8899924755096436, 3.0]

In [87]:
boxxyxy

array([   -0.82776,    0.005127,      132.65], dtype=float32)

In [78]:
results[1]

array([     137.83,      1.4649,      224.85,       142.3,     0.67083,           3], dtype=float32)

In [45]:
from ultralytics import YOLO

model = YOLO(r"ultralytics\best.onnx", task='detect')

In [73]:
# results = model(r"ultralytics\dataset\images\val\pitted_surface_77.jpg")
results=model.predict(
    source=r"ultralytics\dataset\images\val\pitted_surface_77.jpg",
    conf=0.5,
    iou=0.45,                   # 设置NMS的IoU阈值
    device="cpu"               # 可选择使用GPU
)

array=[]

for r in results:
    boxes=r.boxes
    for box in boxes:
        arraybox=[]
        arraybox.append(box.xyxy.numpy().tolist()[0])
        arraybox.append(box.conf.numpy().tolist()[0])
        arraybox.append(box.cls.numpy().tolist()[0])
        array.append(arraybox)
    print(array)


image 1/1 d:\AS\project1\ultralytics\dataset\images\val\pitted_surface_77.jpg: 224x224 2 pitted_surfaces, 6.1ms
Speed: 0.4ms preprocess, 6.1ms inference, 0.4ms postprocess per image at shape (1, 3, 224, 224)
[[[0.0, 0.0, 119.03095245361328, 200.0], 0.8899924755096436, 3.0], [[122.58252716064453, 1.605265498161316, 200.0, 128.7036895751953], 0.5607591271400452, 3.0]]


In [ ]:
[[[0.0, 0.0, 119.03095245361328, 200.0]], [0.8899924755096436], [3.0], [[122.58252716064453, 1.605265498161316, 200.0, 128.7036895751953]], [0.5607591271400452], [3.0]]

In [3]:
from yolodetect import ONNX_Inference
Onnxmodel_path=r"ultralytics\best.onnx"
providers="cpu"
Image_path=r"ultralytics\dataset\images\val\pitted_surface_77.jpg"
confidence_threshold=0.5
imgs=224
array=ONNX_Inference.ModelInferenceByYOLO(Onnxmodel_path,providers,Image_path,confidence_threshold=0.5,imgs=224)

Loading ultralytics\best.onnx for ONNX Runtime inference...
Using ONNX Runtime CPUExecutionProvider

image 1/1 d:\AS\project1\ultralytics\dataset\images\val\pitted_surface_77.jpg: 224x224 2 pitted_surfaces, 7.5ms
Speed: 3.5ms preprocess, 7.5ms inference, 0.7ms postprocess per image at shape (1, 3, 224, 224)


In [2]:
array

[[[-0.8277587890625, 0.005126953125, 132.6519012451172],
  0.8873264789581299,
  3.0],
 [[137.8266143798828, 1.4649200439453125, 224.84963989257812],
  0.6708325743675232,
  3.0]]

In [4]:
array

[[[0.0, 0.0, 119.03095245361328, 200.0], 0.8899924755096436, 3.0],
 [[122.58252716064453, 1.605265498161316, 200.0, 128.7036895751953],
  0.5607591271400452,
  3.0]]

In [1]:
import app
from PIL import Image
label=['crazing', 'inclusion', 'patches', 'pitted_surface', 'rolled-in_scale', 'scratches']
Image_path=r"ultralytics\dataset\images\val\pitted_surface_77.jpg"
Onnxmodel_path=r"ultralytics\best.onnx"

In [2]:
image=Image.open(Image_path).resize((224,224))

In [4]:
results=app.get_model_pridict(Onnxmodel_path=Onnxmodel_path,providers='cpu',input_image=image,confidience=0.5,imgs=224)

In [5]:

# img = Image.open(Image_path).resize((imgs, imgs))
testresult=app.add_bboxs_on_img(label,image,results)

In [6]:
testresult.show()